views:
  side:
    prefix: '1_'
    suffix: '_side'
    zoom_factor: 1.1
    rotate: '315,360,405'
    pan: '0,0.4,0'
    light_elevation: 30
    side: 'top'  # (top, bottom, left, right, front, back)
    
  top:
    prefix: '2_'
    suffix: '_top'
    zoom_factor: 1.1
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'top'
    
  bottom:
    prefix: '3_'
    suffix: '_bottom'
    zoom_factor: 1.1
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'bottom'
    
  left:
    prefix: '4_'
    suffix: '_left'
    zoom_factor: 1.5
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'left'
    
  right:
    prefix: '5_'
    suffix: '_right'
    zoom_factor: 1.5
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'right'
    
  front:
    prefix: '6_'
    suffix: '_front'
    zoom_factor: 1.3
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'front'
    
  back:
    prefix: '7_'
    suffix: '_back'
    zoom_factor: 1.3
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'back'

  side_full:
    prefix: '8_'
    suffix: '_side_full'
    zoom_factor: 1.4
    rotate: '315,360,405'
    pan: '0,0.4,0'
    light_elevation: 30
    side: 'top'  # (top, bottom, left, right, front, back)
    show_footprints:
      - J10
      - J7
    
  top_full:
    prefix: '9_'
    suffix: '_top_full'
    zoom_factor: 1.1
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'top'
    
  bottom_full:
    prefix: '10_'
    suffix: '_bottom_full'
    zoom_factor: 1.1
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'bottom'
    
  left_full:
    prefix: '11_'
    suffix: '_left_full'
    zoom_factor: 1.5
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'left'
    
  right_full:
    prefix: '12_'
    suffix: '_right_full'
    zoom_factor: 1.5
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'right'
    
  front_full:
    prefix: '13_'
    suffix: '_front_full'
    zoom_factor: 1.5
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'front'
    
  back_full:
    prefix: '14_'
    suffix: '_back_full'
    zoom_factor: 1.5
    rotate: '0,0,0'
    pan: '0,-1.5,0'
    light_elevation: 10
    side: 'back'

defaults:
  zoom_factor: 1.0
  rotate: '0,0,0'
  pan: '0,0,0'
  light_elevation: 60
  side: 'top'
